/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.jsf2demo.beans;

import javax.enterprise.context.RequestScoped;
import javax.inject.Named;

/**
 *
 * @author Jeffrey McMullen II
 */
@Named (value = "timeBean")
@RequestScoped
public class TimeBean 
{

    /**
     * Creates a new instance of TimeBean
     */
    public TimeBean() 
    {
        
    }
    
    /**
     * Gets the current date and time of day.
     * @return A String generated by java.util.Date().
     */
    public String getTime() 
    {
        return new java.util.Date().toString();
    }
}
